# Generated by Django 5.2.7 on 2025-10-29 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoutedPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("birth_date", models.DateField(verbose_name="Data de nascimento")),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="Nacionalidade"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "Goleiro"),
                            ("RB", "Lateral direito"),
                            ("LB", "Lateral esquerdo"),
                            ("CB", "Zagueiro"),
                            ("DM", "Volante"),
                            ("CM", "Meia central"),
                            ("AM", "Meia ofensivo"),
                            ("RW", "Ponta direita"),
                            ("LW", "Ponta esquerda"),
                            ("ST", "Atacante"),
                        ],
                        max_length=2,
                        verbose_name="Posição",
                    ),
                ),
                (
                    "current_club",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Clube atual"
                    ),
                ),
                (
                    "market_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor de mercado",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MONITORING", "Monitorando"),
                            ("INTERESTED", "Interessado"),
                            ("NEGOTIATING", "Negociando"),
                        ],
                        default="MONITORING",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="scouting/players/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scouted_players",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jogador observado",
                "verbose_name_plural": "Jogadores observados",
                "ordering": ["-created_at"],
            },
        ),
    ]
