# Generated by Django 5.2.7 on 2025-10-29 01:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scouting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoutingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="Data do relatório")),
                (
                    "match_or_event",
                    models.CharField(
                        max_length=200, verbose_name="Partida ou evento observado"
                    ),
                ),
                (
                    "technical_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Avaliação técnica",
                    ),
                ),
                (
                    "physical_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Avaliação física",
                    ),
                ),
                (
                    "tactical_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Avaliação tática",
                    ),
                ),
                (
                    "mental_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Avaliação mental",
                    ),
                ),
                (
                    "potential_score",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Potencial",
                    ),
                ),
                ("strengths", models.TextField(verbose_name="Pontos fortes")),
                ("weaknesses", models.TextField(verbose_name="Pontos a desenvolver")),
                ("recommendation", models.TextField(verbose_name="Recomendação final")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scouting_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Observador",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="scouting.scoutedplayer",
                        verbose_name="Jogador observado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório de scouting",
                "verbose_name_plural": "Relatórios de scouting",
                "ordering": ["-report_date", "-created_at"],
            },
        ),
    ]
