# Generated by Django 5.2.7 on 2025-10-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scouting", "0002_scoutingreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoutedplayer",
            name="hire_date",
            field=models.DateField(
                blank=True,
                help_text="Data em que o jogador foi contratado",
                null=True,
                verbose_name="Data de contratação",
            ),
        ),
        migrations.AlterField(
            model_name="scoutedplayer",
            name="status",
            field=models.CharField(
                choices=[
                    ("MONITORING", "Monitorando"),
                    ("INTERESTED", "Interessado"),
                    ("NEGOTIATING", "Negociando"),
                    ("HIRED", "Contratado"),
                ],
                default="MONITORING",
                max_length=15,
                verbose_name="Status",
            ),
        ),
    ]
