# Generated by Django 5.2.7 on 2025-10-28 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nome")),
                ("birth_date", models.DateField(verbose_name="Data de nascimento")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("GK", "Goleiro"),
                            ("DF", "Defensor"),
                            ("MF", "Meio-campo"),
                            ("FW", "Atacante"),
                        ],
                        max_length=2,
                        verbose_name="Posição",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="Nacionalidade"),
                ),
                ("height", models.FloatField(verbose_name="Altura (cm)")),
                ("weight", models.FloatField(verbose_name="Peso (kg)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athletes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atleta",
                "verbose_name_plural": "Atletas",
                "ordering": ["-created_at"],
            },
        ),
    ]
