# Generated by Django 5.2.7 on 2025-10-29 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(verbose_name='Data do treino')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Duração (minutos)')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Distância (km)')),
                ('heart_rate_avg', models.PositiveIntegerField(blank=True, null=True, verbose_name='FC média')),
                ('heart_rate_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='FC máxima')),
                ('intensity_level', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('VERY_HIGH', 'Muito Alta')], max_length=10, verbose_name='Intensidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_loads', to='performance.athlete', verbose_name='Atleta')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_loads', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Carga de treino',
                'verbose_name_plural': 'Cargas de treino',
                'ordering': ['-training_date', '-created_at'],
            },
        ),
    ]
