# Generated by Django 5.2.7 on 2025-10-29 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0002_trainingload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InjuryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("injury_date", models.DateField(verbose_name="Data da lesão")),
                (
                    "injury_type",
                    models.CharField(
                        choices=[
                            ("MUSCULAR", "Muscular"),
                            ("ARTICULAR", "Articular"),
                            ("OSSEOUS", "Óssea"),
                            ("LIGAMENT", "Ligamentar"),
                            ("TENDON", "Tendínea"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de lesão",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        choices=[
                            ("KNEE", "Joelho"),
                            ("ANKLE", "Tornozelo"),
                            ("THIGH", "Coxa"),
                            ("HAMSTRING", "Posterior da coxa"),
                            ("SHOULDER", "Ombro"),
                            ("BACK", "Costas"),
                        ],
                        max_length=20,
                        verbose_name="Parte do corpo",
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("LEVE", "Leve"),
                            ("MODERADA", "Moderada"),
                            ("GRAVE", "Grave"),
                        ],
                        max_length=10,
                        verbose_name="Gravidade",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "expected_return",
                    models.DateField(
                        blank=True, null=True, verbose_name="Retorno previsto"
                    ),
                ),
                (
                    "actual_return",
                    models.DateField(
                        blank=True, null=True, verbose_name="Retorno real"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injury_records",
                        to="performance.athlete",
                        verbose_name="Atleta",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injury_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de lesão",
                "verbose_name_plural": "Registros de lesões",
                "ordering": ["-injury_date", "-created_at"],
            },
        ),
    ]
