# Generated by Django 5.2.7 on 2025-10-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_injuryrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="market_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor estimado do atleta em Reais (R$)",
                max_digits=12,
                null=True,
                verbose_name="Valor de Mercado",
            ),
        ),
    ]
