# Generated by Django 5.2.7 on 2025-10-29 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do clube",
                        max_length=200,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="País onde o clube está localizado",
                        max_length=100,
                        verbose_name="País",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Cidade sede do clube",
                        max_length=100,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("PRIMEIRA", "Primeira Divisão"),
                            ("SEGUNDA", "Segunda Divisão"),
                            ("TERCEIRA", "Terceira Divisão"),
                            ("QUARTA", "Quarta Divisão"),
                            ("OUTRA", "Outra"),
                        ],
                        default="PRIMEIRA",
                        help_text="Divisão em que o clube compete",
                        max_length=20,
                        verbose_name="Divisão",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo do clube (opcional)",
                        null=True,
                        upload_to="clubs/logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clubs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clube",
                "verbose_name_plural": "Clubes",
                "ordering": ["-created_at"],
            },
        ),
    ]
