# Generated by Django 5.2.7 on 2025-10-29 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(
                        help_text="Data em que a transação ocorreu",
                        verbose_name="Data do Registro",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SALARIOS", "Salários"),
                            ("TRANSFERENCIAS", "Transferências"),
                            ("INFRAESTRUTURA", "Infraestrutura"),
                            ("MARKETING", "Marketing"),
                            ("OUTROS", "Outros"),
                        ],
                        help_text="Categoria do registro financeiro",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor da transação em reais (deve ser maior que 0)",
                        max_digits=12,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("RECEITA", "Receita"), ("DESPESA", "Despesa")],
                        help_text="Tipo de transação: receita ou despesa",
                        max_length=10,
                        verbose_name="Tipo de Transação",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição detalhada do registro financeiro",
                        verbose_name="Descrição",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        help_text="Clube relacionado ao registro financeiro",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_records",
                        to="business.club",
                        verbose_name="Clube",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro Financeiro",
                "verbose_name_plural": "Registros Financeiros",
                "ordering": ["-record_date"],
            },
        ),
    ]
