# Generated by Django 5.2.7 on 2025-10-29 03:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_financialrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Ano da receita (entre 2000 e 2100)",
                        validators=[
                            django.core.validators.MinValueValidator(
                                2000, message="O ano deve ser maior ou igual a 2000."
                            ),
                            django.core.validators.MaxValueValidator(
                                2100, message="O ano deve ser menor ou igual a 2100."
                            ),
                        ],
                        verbose_name="Ano",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        help_text="Mês da receita (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="O mês deve estar entre 1 e 12."
                            ),
                            django.core.validators.MaxValueValidator(
                                12, message="O mês deve estar entre 1 e 12."
                            ),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "ticketing",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Receita de venda de ingressos",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="A bilheteria não pode ser negativa."
                            )
                        ],
                        verbose_name="Bilheteria",
                    ),
                ),
                (
                    "sponsorship",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Receita de contratos de patrocínio",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="O patrocínio não pode ser negativo."
                            )
                        ],
                        verbose_name="Patrocínio",
                    ),
                ),
                (
                    "broadcasting",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Receita de direitos de transmissão de jogos",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0,
                                message="Os direitos de transmissão não podem ser negativos.",
                            )
                        ],
                        verbose_name="Direitos de Transmissão",
                    ),
                ),
                (
                    "merchandising",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Receita de venda de produtos oficiais",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="O merchandising não pode ser negativo."
                            )
                        ],
                        verbose_name="Merchandising",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        help_text="Clube relacionado às receitas",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenues",
                        to="business.club",
                        verbose_name="Clube",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita Mensal",
                "verbose_name_plural": "Receitas Mensais",
                "ordering": ["-year", "-month"],
                "unique_together": {("club", "year", "month")},
            },
        ),
    ]
